import type { CardValue, Suit } from '../types';

export const SITE_URL = (import.meta.env.VITE_SITE_URL || 'https://trucardo.sytes.net').replace(/\/$/, '');
export const BRAND = 'TRUCARDO';
export interface Section { heading: string; text?: string[]; items?: string[]; table?: { headers: string[]; rows: string[][] }; visual?: 'ranking' | 'envido' | 'flor' }
export interface SeoContent { path: string; title: string; description: string; heading: string; intro: string; sections: Section[]; related: string[] }
export const homeMeta = {
  title: 'Truco online con amigos desde el celular | TRUCARDO',
  description: 'Jugá al Truco online con amigos desde el celular. Creá una mesa, compartí el QR y repartí cartas españolas. Sin registro, sin descargar apps y con turnos.',
};
export const ranking: { label: string; value: CardValue; suits: Suit[] }[] = [
  { label:'Ancho de espada', value:1, suits:['espada'] }, { label:'Ancho de basto', value:1, suits:['basto'] },
  { label:'Siete de espada', value:7, suits:['espada'] }, { label:'Siete de oro', value:7, suits:['oro'] },
  ...([3,2] as const).map(value=>({label:`Todos los ${value}`,value,suits:['espada','basto','oro','copa'] as Suit[]})),
  { label:'Anchos falsos: oro y copa', value:1, suits:['oro','copa'] },
  ...([12,11,10] as const).map(value=>({label:`Todos los ${value}`,value,suits:['espada','basto','oro','copa'] as Suit[]})),
  { label:'Sietes de basto y copa', value:7, suits:['basto','copa'] },
  ...([6,5,4] as const).map(value=>({label:`Todos los ${value}`,value,suits:['espada','basto','oro','copa'] as Suit[]})),
];
export const pages: SeoContent[] = [
  { path:'/truco/', title:'Truco argentino: reglas, cartas y envido | TRUCARDO', description:'Aprendé a jugar al Truco argentino: reglas, valor de las cartas, señas, envido, flor y puntuación. Consultá las guías y creá una mesa con tus amigos.', heading:'Truco argentino: aprendé y llevá la mesa al celular', intro:'El Truco mezcla cartas, memoria y conversación. Acá encontrás una guía para entender cada parte del juego y una mesa online para jugar con tus amigos.',
    sections:[{heading:'Qué necesitás para empezar',text:['Se juega con una baraja española de 40 cartas: espada, basto, oro y copa. Cada palo tiene 1 al 7, 10, 11 y 12. Cada jugador recibe tres cartas.','TRUCARDO conecta mesas de 2, 3, 4 o 6 personas. No necesitás cartas físicas: creá una mesa y compartí el código o el QR. Los cantos se hacen hablando, presencialmente o por una llamada.']},{heading:'Elegí lo que querés aprender',text:['Si es tu primera partida, empezá por «Cómo jugar». Si ya conocés el juego, las páginas de cartas, envido y puntuación sirven como consulta durante una mano.']},{heading:'Del reglamento a tu mesa',text:['Las variantes de Flor, Falta Envido y Gallo pueden cambiar según la región. Acuerden esas reglas antes de repartir. La aplicación controla las cartas y los turnos; el anfitrión anota los tantos que acuerde la mesa.']}],related:['/truco/como-jugar/','/truco/reglas/','/truco/cartas/','/truco/senas/','/truco/envido/','/truco/flor/','/truco/puntuacion/','/juegos/truco/'] },
  { path:'/truco/como-jugar/', title:'Cómo jugar al Truco argentino paso a paso | TRUCARDO', description:'Aprendé cómo jugar al Truco argentino: reparto, mano, turnos, bazas y cantos. Una guía para tu primera partida y para jugar online con amigos.', heading:'Cómo jugar al Truco argentino', intro:'Cada jugador recibe tres cartas. El objetivo es sumar los puntos de la partida, ganando manos y cantos de Truco o Envido. Se suele jugar a 15 o 30 tantos.',
    sections:[{heading:'1. Armá la mesa',text:['Dos personas juegan mano a mano. De a cuatro o seis, se forman dos equipos con asientos alternados. En TRUCARDO también podés jugar de a tres: el repartidor es gallo y enfrenta a los otros dos.']},{heading:'2. Repartí y ubicá a mano',text:['Se reparten tres cartas a cada persona. Mano es quien está a la derecha del repartidor y juega primero. En la aplicación es el asiento siguiente al que reparte; el orden aparece en la lista de jugadores.']},{heading:'3. Jugá las bazas',items:['Cada persona tira una carta cuando le toca.','La carta de mayor jerarquía gana la baza y su jugador abre la siguiente.','La mano se decide por las bazas ganadas y las reglas de parda; puede terminar antes de jugar las tres cartas.']},{heading:'4. Cantá y respondé',text:['El Truco aumenta los puntos en disputa. El Envido compara los tantos de las cartas y se canta en la primera baza, antes de jugar tu primera carta. A cada propuesta se responde «quiero» o «no quiero».']},{heading:'5. Jugá desde el celular',items:['Creá la mesa y elegí cuántos van a jugar.','Compartí el QR o el código; cada participante entra con un nombre.','Cuando te toque, usá «Ver y elegir carta» y confirmá «Tirar carta».','Anoten los puntos y repartan otra mano. El repartidor y mano rotan.']}],related:['/truco/cartas/','/truco/reglas/','/truco/envido/','/truco/puntuacion/'] },
  { path:'/truco/reglas/', title:'Reglas del Truco argentino y pardas | TRUCARDO', description:'Consultá las reglas del Truco argentino: turnos, equipos, mano, pardas y cómo se gana cada mano. Acordá las variantes y jugá con amigos en TRUCARDO.', heading:'Reglas del Truco argentino', intro:'La versión de TRUCARDO usa 40 cartas españolas, tres cartas por jugador y turnos por asiento. Los cantos y la anotación de sus puntos quedan a cargo de los jugadores.',
    sections:[{heading:'Quién juega primero',text:['Mano abre la primera baza. Después sale quien ganó la anterior. Cuando las cartas máximas empatan entre compañeros, gana su equipo y sale el primero que tiró una de esas cartas. Si son de bandos distintos, la baza es parda.']},{heading:'Cómo se resuelven las pardas',table:{headers:['Resultado de las bazas','Quién gana la mano'],rows:[['Un equipo gana primera y segunda','Ese equipo; no hace falta la tercera'],['Primera ganada, segunda parda','Quien ganó la primera'],['Primera parda, segunda ganada','Quien ganó la segunda'],['Cada equipo gana una; tercera ganada','Quien gana la tercera'],['Cada equipo gana una; tercera parda','Quien ganó la primera'],['Primera y segunda pardas','Se juega la tercera'],['Tres pardas','El equipo de mano']]}},{heading:'Equipos y Gallo en TRUCARDO',text:['De a cuatro y seis, los asientos pares forman un equipo y los impares el otro. De a tres, el repartidor juega solo esa mano y el gallo rota con cada reparto. Cada persona tiene un marcador individual.','En esta aplicación todos reciben tres cartas. Existen variantes de Gallo con cuatro cartas y descarte; ese reparto no está implementado.']},{heading:'Qué acuerda la mesa',items:['Meta de 15 o 30 puntos.','Si se juega con Flor y qué subidas se permiten.','Cómo calculan Falta Envido en malas y buenas.','Si rechazan Truco o se van al mazo, anoten los tantos y cierren la mano antes de repartir otra.']}],related:['/truco/como-jugar/','/truco/cartas/','/truco/puntuacion/','/truco/flor/'] },
  { path:'/truco/cartas/', title:'Valor de las cartas del Truco: orden completo | TRUCARDO', description:'Mirá el valor de las 40 cartas del Truco argentino, de mayor a menor, con ilustraciones de cada palo. Diferenciá jerarquía de Truco y valor de Envido.', heading:'Valor de las cartas del Truco', intro:'La carta más fuerte es el 1 de espada. Después vienen el 1 de basto, el 7 de espada y el 7 de oro. La fuerza para ganar una baza no coincide con el valor para contar Envido.',
    sections:[{heading:'Jerarquía completa, de mayor a menor',text:['Las cartas de una misma fila tienen la misma fuerza. Un 3 de copa puede empardar con un 3 de oro; un 7 de espada supera a un 7 de copa.'],visual:'ranking'},{heading:'Figuras y cartas bajas',text:['El rey (12) le gana al caballo (11), que le gana a la sota (10). Los sietes de copa y basto van después de las figuras. Luego vienen 6, 5 y 4, de mayor a menor.']},{heading:'No confundas Truco con Envido',text:['Para Truco importa esta jerarquía. Para Envido, del 1 al 7 cuenta el número y las figuras valen cero. Por eso un 7 y un 6 del mismo palo pueden dar 33 de Envido aunque el 6 sea una carta baja para las bazas.']}],related:['/truco/envido/','/truco/senas/','/truco/reglas/'] },
  { path:'/truco/senas/', title:'Señas del Truco argentino: cartas y gestos | TRUCARDO', description:'Conocé las señas habituales del Truco: ancho de espada, ancho de basto, sietes, treses y doses. Acordá los gestos con tu compañero antes de jugar.', heading:'Señas del Truco argentino', intro:'Las señas permiten avisarle al compañero qué cartas tenés sin decirlo en voz alta. Estos gestos son habituales, pero pueden variar entre mesas y regiones.',
    sections:[{heading:'Cartas y señas habituales',table:{headers:['Carta','Seña habitual'],rows:[['1 de espada','Levantar las cejas'],['1 de basto','Guiñar un ojo'],['7 de espada','Mover la boca hacia la derecha'],['7 de oro','Mover la boca hacia la izquierda'],['Un 3','Morder el labio inferior'],['Un 2','Hacer el gesto de un beso'],['1 de oro o de copa','Abrir la boca'],['Cartas bajas, sin fuerza','Cerrar ambos ojos']]}},{heading:'Acordá el código antes de repartir',text:['Confirmen qué significa cada gesto y eviten confundir derecha e izquierda. Las señas ayudan a coordinar quién guarda una carta fuerte y quién necesita apoyo.','No hay una seña única universal para cada cantidad de Envido. Pueden acordar un código propio si su reglamento permite señas.']},{heading:'Cómo usarlas con TRUCARDO',text:['Si están en la misma mesa, las señas se hacen cara a cara. Si juegan a distancia, necesitan su propia videollamada. La aplicación no incluye cámara ni transmite señas, y solo publica las cartas que ya tiraron.']}],related:['/truco/cartas/','/truco/envido/','/juegos/truco/'] },
  { path:'/truco/envido/', title:'Cómo contar el Envido: valores y ejemplos | TRUCARDO', description:'Aprendé cómo contar el Envido: cartas del mismo palo, figuras que valen cero y ejemplos de 33, 25, 20 y 7 puntos. Consultá los cantos y sus valores.', heading:'Cómo contar el Envido', intro:'Con dos cartas del mismo palo, sumá sus valores y agregá 20. Del 1 al 7 vale el número; el 10, el 11 y el 12 valen cero. El máximo de Envido es 33.',
    sections:[{heading:'Ejemplos con cartas españolas',visual:'envido'},{heading:'Si tenés tres palos distintos',text:['Cuenta el número de Envido más alto de las tres cartas, sin sumar 20. Si las tres son figuras de distintos palos, tenés cero.','Si tenés tres cartas del mismo palo y juegan sin Flor, elegí las dos que más suman para contar Envido. Si juegan con Flor, consultá sus reglas antes de cantar.']},{heading:'Cuánto valen los cantos',table:{headers:['Canto aceptado','Puntos en juego'],rows:[['Envido','2'],['Real Envido','3'],['Envido + Envido','4'],['Envido + Real Envido','5'],['Envido + Envido + Real Envido','7']]}},{heading:'Cuándo cantarlo y cómo desempatar',text:['Cantalo durante la primera baza, antes de jugar tu primera carta. Si aceptan, gana quien tenga más tantos. Ante igualdad, tiene prioridad quien aparece primero en el orden desde mano. Los tantos deben poder comprobarse con las cartas.','Falta Envido depende de la meta y de la variante que hayan acordado. TRUCARDO no calcula ese canto automáticamente: el anfitrión anota el valor que corresponda.']}],related:['/truco/flor/','/truco/puntuacion/','/truco/cartas/'] },
  { path:'/truco/flor/', title:'Flor en el Truco: qué es y cuánto vale | TRUCARDO', description:'Entendé la Flor en el Truco argentino: tres cartas del mismo palo, cómo contar sus tantos y por qué cambia el Envido. Acordá esta variante con tu mesa.', heading:'Qué es la Flor en el Truco', intro:'Tenés Flor cuando tus tres cartas son del mismo palo. Es una modalidad opcional: algunas mesas juegan con Flor y otras sin ella. Acuerden la variante antes de empezar.',
    sections:[{heading:'Una Flor con cartas españolas',visual:'flor',text:['Para comparar Flores se suman los valores de las tres cartas y se agregan 20; las figuras valen cero. Eso es distinto del Envido, que usa dos cartas.']},{heading:'Cuántos puntos suma',text:['Una Flor sin rival vale habitualmente 3 puntos. Si hay Flores enfrentadas pueden entrar en juego Contra Flor y Contra Flor al Resto. Sus respuestas, valores y momento de anunciarla dependen del reglamento elegido.']},{heading:'Qué pasa con el Envido',text:['Cuando juegan con Flor y se anuncia una, el lance de Envido no se disputa. Cuando juegan sin Flor, tres cartas del mismo palo se cuentan para Envido eligiendo las dos que más suman.']},{heading:'Flor en la aplicación',text:['TRUCARDO reparte y controla las bazas, pero no canta Flor ni determina sus subidas automáticamente. Anuncien sus cantos hablando y usen el marcador para sumar o corregir los tantos.']}],related:['/truco/envido/','/truco/reglas/','/truco/puntuacion/'] },
  { path:'/truco/puntuacion/', title:'Puntos del Truco y Envido: tabla de cantos | TRUCARDO', description:'Consultá cuántos puntos valen Truco, Retruco, Vale cuatro y Envido, aceptados o rechazados. Usá el anotador compartido de TRUCARDO para jugar a 15 o 30.', heading:'Puntuación del Truco y del Envido', intro:'Los puntos del Truco y del Envido se anotan por separado. La mano sin cantar Truco vale 1 punto; aceptar Truco la sube a 2, Retruco a 3 y Vale cuatro a 4.',
    sections:[{heading:'Truco querido y no querido',table:{headers:['Canto','Si aceptan','Si rechazan'],rows:[['Sin cantar Truco','1','—'],['Truco','2','1'],['Retruco','3','2'],['Vale cuatro','4','3']]}},{heading:'Envido y subidas',table:{headers:['Canto','Si aceptan','Si rechazan la última subida'],rows:[['Envido','2','1'],['Real Envido','3','1'],['Envido + Envido','4','2'],['Envido + Real Envido','5','2'],['Envido + Envido + Real Envido','7','4']]}},{heading:'Falta Envido y Flor',text:['Falta Envido no tiene un número fijo: depende del tanteador y de la variante acordada. Una forma habitual cuenta lo que le falta al equipo que va adelante para alcanzar la meta; otras distinguen malas y buenas.','Si juegan con Flor, una Flor sin rival suma habitualmente 3. Acuerden las subidas y anoten sus valores manualmente.']},{heading:'Anotar en TRUCARDO',items:['Elegí 15 o 30 antes de empezar.','El anfitrión selecciona los puntos por anotación y usa + para sumarlos.','El botón − corrige una anotación.','Los puntos se conservan entre manos. En Gallo cada persona tiene su propio marcador.','Al cerrar la mesa se borran cartas y marcador; no se guarda un historial de partidas.']}],related:['/truco/envido/','/truco/flor/','/juegos/truco/'] },
  { path:'/juegos/', title:'Juegos de cartas españolas online | TRUCARDO', description:'Descubrí los juegos disponibles en TRUCARDO. Creá una mesa de Truco argentino online con amigos, repartí cartas españolas y compartí el QR para empezar.', heading:'Juegos de cartas españolas en TRUCARDO', intro:'El juego disponible es Truco argentino. La mesa reúne el reparto de cartas, los turnos, las bazas y un anotador compartido para jugar con gente que conocés.',
    sections:[{heading:'Truco argentino con amigos',text:['Podés crear mesas de 2, 3, 4 o 6 jugadores. Cada participante entra desde su navegador con un nombre; no se pide correo ni contraseña.','Las cartas por tirar son privadas. Al confirmar una jugada, la carta aparece en la mesa de todos. Los cantos se hacen hablando.']},{heading:'Elegí tu próxima partida',text:['Si ya sabés jugar, entrá a la mesa de Truco. Si necesitás repasar, las guías explican las reglas, las cartas y cómo contar Envido.','Escoba y Chinchón todavía no están disponibles en TRUCARDO.']}],related:['/juegos/truco/','/truco/como-jugar/','/repartir-cartas/'] },
  { path:'/juegos/truco/', title:'Jugar Truco online con amigos por QR | TRUCARDO', description:'Creá una mesa de Truco online con amigos. Compartí el QR, repartí cartas y jugá por turnos desde el celular, sin registro ni descargar una aplicación.', heading:'Jugá al Truco online con amigos', intro:'Tu grupo, una mesa compartida y tres cartas privadas para cada jugador. TRUCARDO funciona en el navegador del celular y también en una computadora.',
    sections:[{heading:'Crear mesa → compartir QR → jugar',items:['Elegí un nombre y una mesa de 2, 3, 4 o 6 personas.','Compartí el enlace, el código o el QR con tus amigos.','Cuando estén todos, el anfitrión o repartidor entrega las cartas.','Cada persona juega cuando le toca. La aplicación resuelve las bazas y las pardas.']},{heading:'Una mesa para tu grupo',text:['Podés jugar presencialmente o a distancia. TRUCARDO no empareja con desconocidos ni incluye chat o llamadas: para los cantos usen la conversación de la mesa o su llamada habitual.']},{heading:'Sin registro y con cartas privadas',text:['Solo ingresás un nombre. Cada navegador conserva una identidad anónima que permite acceder a tus cartas; volver con ese mismo navegador recupera la mesa mientras siga activa.','El anfitrión puede cerrar la mesa, lo que borra cartas, jugadores y marcador. Las mesas inactivas vencen y se limpian automáticamente.']}],related:['/truco/como-jugar/','/truco/puntuacion/','/repartir-cartas/'] },
  { path:'/repartir-cartas/', title:'Repartir cartas españolas online para Truco | TRUCARDO', description:'Usá TRUCARDO como repartidor de cartas españolas online para Truco. Tres cartas privadas por jugador, mesas por QR y nuevo reparto al terminar cada mano.', heading:'Repartidor de cartas españolas online', intro:'Si querés jugar al Truco y no tenés una baraja a mano, TRUCARDO reparte tres cartas españolas a cada participante y las muestra solo en su propio navegador.',
    sections:[{heading:'Qué reparte TRUCARDO',text:['El mazo tiene 40 cartas, sin 8 ni 9. Se mezclan y se reparten tres por persona en mesas completas de 2, 3, 4 o 6 jugadores. Una misma carta no se repite entre las manos del reparto.','El reparto actual está pensado para Truco. No permite elegir una cantidad arbitraria de cartas ni jugar Escoba o Chinchón.']},{heading:'Cómo compartir el mazo',items:['Creá una mesa y elegí la cantidad de jugadores.','Invitá a cada persona mediante el código o el QR.','Repartí cuando la mesa esté completa.','Mantené apretado para mirar o, en tu turno, elegí una carta y tirala a la mesa.']},{heading:'Cada mano empieza de nuevo',text:['Al repartir otra mano rota el repartidor, se mezcla el mazo y se reemplazan las cartas anteriores. El marcador se mantiene hasta cerrar la mesa.','Las cartas jugadas se ven en la mesa compartida y las restantes siguen privadas. Para conectar celulares todos necesitan conexión a Internet.']}],related:['/juegos/truco/','/truco/cartas/','/truco/como-jugar/'] },
];
export function normalizePath(path: string) { return path === '/' ? path : `${path.replace(/\/+$/, '')}/`; }
export function getPage(path: string) { return pages.find(page=>page.path === normalizePath(path)); }
export const sources = [
  {label:'Reglamento del Truco · CASI',href:'https://www.casi.com.ar/sites/default/files/Reglamento%20Truco.pdf'},
  {label:'Reglas del Truco Argentino',href:'https://www.trucoargentino.com.ar/reglas/'},
];
